### ISSUE TITLE
Very slow inference on cuda

### ISSUE THREAD

**Issue by Ludvig-Joborn** [audiolabs/torch-pesq#3]
Hi! 
First of all, thank you for this repository! I have already found great joy in finding out there is a pytorch implementation of PESQ, and I really look forward to migrating away from the reference PESQ-repository.

With that said, I'm having performance issues when sending the module to cuda. Moving the module from cpu to cuda to move inference time from ~0.06 seconds to ~40 seconds. The audio files I'm using are 10 seconds long with 16 kHz sampling rate. I'm including a sample clip:
[clean_fileid_1.zip](https://github.com/audiolabs/torch-pesq/files/11287248/clean_fileid_1.zip)

My environment is as follows: 

- pytorch 1.13.0+cu117.
- numpy 1.22.4,
- scipy 1.7.3
- torchaudio 0.13.0
- torchtyping 0.1.4
- typeguard 3.0.2

Below is a minimal example.
```
import torchaudio
from pesq import pesq as pesq_ref_calc
from torch_pesq import PesqLoss
from time import time
import torch


def speed_test(file, device):
    pesq_torch_calc = PesqLoss(1.0, sample_rate=16000).to(device)

    audio, sr = torchaudio.load(file)
    assert sr == 16000

    audio = audio.to(device)

    s_time = time()
    reference_pesq = pesq_ref_calc(
        sr, audio.squeeze().cpu().numpy(), audio.squeeze().cpu().numpy()
    )
    e_time = time()
    print(f"{device} - reference time: {e_time-s_time}")

    s_time = time()
    torch_pesq = pesq_torch_calc.mos(ref=audio, deg=audio)
    e_time = time()
    print(f"{device} - reference time: {e_time-s_time}")


if __name__ == "__main__":
    print(torch.__version__)
    file = "/media/ludvigj/Elements/DNS_1000h/training_set_dec20/train/clean/clean_fileid_1.wav"
    speed_test(file, device="cpu")
    speed_test(file, device="cuda")
```
prints:
cpu - reference time: 0.26168298721313477
cpu - torchpesq time: 0.060210227966308594
cuda - reference time: 0.25937652587890625
cuda - torchpesq time: 40.94913053512573

I don't know why this happens but would greatly appreciate help in figuring out how to cuda-accelerate the PESQ calculation properly.
Let me know if I've misunderstood something, or if there's any further helpful information I can provide!

**Comment by bytesnake** [comment]
Hi! Interesting effect, can you also provide CUDA version and nvidia card?

**Comment by nils-werner** [comment]
Can you run your code through the pytorch profiler so we can find out what exactly is the culprit?

**Comment by Ludvig-Joborn** [comment]
Alright, so I have made a few more tests to figure out what's going on.
First off, I tried running the program with PyTorch 2.0+cu117, and this problem is entirely gone.

New env:
- **pytorch 2.0.0+cu117**
- **torchaudio 2.0.1+cu117**
- numpy 1.22.4,
- scipy 1.7.3
- torchtyping 0.1.4
- typeguard 3.0.2

With the above environment, I changed the "if name==main"-part like this:
```
if __name__ == "__main__":
    file = "/path/to/audio/clean_fileid_1.wav"
    speed_test(file, device="cpu")
    speed_test(file, device="cuda")

    print("-------- RERUN -------- ")

    speed_test(file, device="cpu")
    speed_test(file, device="cuda")
```
and got the following results:
cpu - reference time: 0.25433897972106934
cpu - torchpesq time: 0.05077409744262695
cuda - reference time: 0.26180601119995117
cuda - torchpesq time: 1.4445228576660156
-------- RERUN -------- 
cpu - reference time: 0.28389716148376465
cpu - torchpesq time: 0.036733150482177734
cuda - reference time: 0.2544569969177246
cuda - torchpesq time: 0.007334470748901367

Now, the code is **much** faster than the reference implementation after the first epoch. Yay!

Old environment outputs the following:
cpu - reference time: 0.27030086517333984
cpu - torchpesq time: 0.05422854423522949
cuda - reference time: 0.2719442844390869
cuda - torchpesq time: 31.54442000389099

-------- RERUN -------- 

cpu - reference time: 0.2565004825592041
cpu - torchpesq time: 0.03466224670410156
cuda - reference time: 0.27118539810180664
cuda - torchpesq time: 30.64244842529297

I will run the profiler shortly to figure out where the problem was located, but it seems to be alleviated in PyTorch 2.0.0 at least!

**Comment by Ludvig-Joborn** [comment]
Alright, so after a little digging I found the following:

The torch profiler was unable to finish running because it ran out of RAM (64 GB was seemingly not enough). But I was able to find the two lines that caused the slowdown issue.

Using
```
import time
tic = time.perf_counter()
ref, deg = self.align_level(ref), self.align_level(deg)
print("Align:", time.perf_counter()-tic)

tic = time.perf_counter()
ref, deg = self.preemphasize(ref), self.preemphasize(deg)
print("Preemphasize:", time.perf_counter()-tic)
```
printed
Align: 17.251407003990607
Preemphasize: 15.467198889004067

What they have in common is using the torchaudio.lfilter()-function. Now since torchaudio 2.0.1 works so well, I'll just stick with that for now. For the record, my nvidia card is GeForce RTX 2080 Ti.

Let me know if I can help out more!

**Comment by bytesnake** [comment]
ah I see, there was a PR for cuda lfilter implementation beginning of this year merged. You can find the relevant tracking issue here https://github.com/pytorch/audio/issues/1408 (and the subsequent PR below). Since [TorchAudio 0.13.1](https://github.com/pytorch/audio/releases/tag/v0.13.1) was released in December last year, you need the newest release tag for performance. 

As a tradeoff we could move the calculation to CPU for older `torchaudio` version or constrain to `torchaudio>=2.0.0`, not sure what the best approach would be @nils-werner

**Comment by Ludvig-Joborn** [comment]
> Maybe the easiest way is to simply emit a warning about bad performance when a GPU & torchaudio<2.0.0 combination was detected, and let the user decide whether to use CPU or upgrade?

I like this approach. It is minimally hassle-some API-wise and clearly informs the user of the problems and the solution.

**Comment by bytesnake** [comment]
Added a warning in https://github.com/audiolabs/torch-pesq/commit/162767d5c82acb7761ed45a100a2fbd93e099127

**Comment by Ludvig-Joborn** [comment]
Thanks guys!
